;; guix mpv
(specifications->manifest
 '("emacs"
   "emacs-guix"
   "emacs-general"
   "emacs-undo-tree"
   "emacs-evil"
   "emacs-evil-collection"
   "emacs-doom-themes"
   "emacs-visual-fill-column"
   "emacs-vertico"
   ;; "emacs-savehist"
   "emacs-marginalia"
   "emacs-rainbow-delimiters"
   "emacs-all-the-icons"
   "emacs-all-the-icons-completion"
   "emacs-doom-modeline"
   "emacs-which-key"
   "emacs-counsel"
   "emacs-helpful"
   "emacs-hydra"
   "emacs-no-littering"
   "emacs-prettier"
   "emacs-org"
   "emacs-org-bullets"
   "emacs-ox-pandoc"
   "emacs-org-appear"
   "emacs-org-super-agenda"
   "emacs-evil-org"
   "emacs-org-roam"
   "emacs-erc-hl-nicks"
   "emacs-erc-image"
   "emacs-emojify"
   ;; "emacs-unicode-fonts"
   ;; "emacs-mu4e"
   "emacs-mu4e-alert"
   "emacs-org-mime"
   "emacs-projectile"
   "emacs-counsel-projectile"
   "emacs-yasnippet"
   "emacs-magit"
   "emacs-lsp-mode"
   "emacs-lsp-ui"
   "emacs-lsp-treemacs"
   "emacs-geiser-guile"
   "emacs-geiser"
   "emacs-smartparens"
   "emacs-company"
   "emacs-company-box"
   ;; "emacs-compile"
   "cmatrix"
   "emacs-vterm"
   "emacs-nord-theme"
   "emacs-password-store"))
